
name: User Story
description: Create a User Story
title: "[Bug]: "
labels: ["bug", "triage"]
body:
- type: dropdown
  id: download
  attributes:
    label: As a
    options:
      - Data Engineer
      - Risk Pricing Analyst
      - Product Development Analyst
      - Data Scientist
      - Master Policy Table Extract
      - Master Claims Data Extract
      - Green List Extract
      - Property/Person DB Extract
  validations:
    required: true
- type: dropdown
  id: download
  attributes:
    label: I want to
    options:
      - add
      - remove
      - change
  validations:
    required: true
- type: markdown
  value: "## Welcome!"
    
    
    
    
    
