name: User Story Build
description: Create a User Story
title: "[User Story]: "

body:
- type: dropdown
  id: download1
  attributes:
    label: As a
    options:
      - Data Engineer
      - Risk Pricing Analyst
      - Product Development Analyst
      - Data Scientist
      - Master Policy Table Extract
      - Master Claims Data Extract
      - Green List Extract
      - Property/Person DB Extract
  validations:
    required: true
- type: dropdown
  id: download2
  attributes:
    label: I want to
    options:
      - add
      - remove
      - change
  validations:
    required: true
- type: textarea
  id: iwantto
  attributes:
    label: ...
    description: 
    placeholder: 
    value: "Please say what you want"
  validations:
    required: true
- type: dropdown
  id: download3
  attributes:
    label: so that I can
    options:
      - view
      - analyse
      - score
      - select
      - report
  validations:
    required: true
- type: textarea
  id: achievegoal
  attributes:
    label: ...
    description: 
    placeholder: 
    value: "Please explain the end goal"
  validations:
    required: true
