name: User Story Build
description: Create a User Story
title: "[User Story]: "

body:
- type: markdown
  attributes:
    value: |
        Thanks for taking the time to fill out this bug report!
- type: dropdown
  id: download1
  attributes:
    label: As a
    options:
      - Data Engineer
      - Risk Pricing Analyst
      - Product Development Analyst
      - Data Scientist
      - Master Policy Table Extract
      - Master Claims Data Extract
      - Green List Extract
      - Property/Person DB Extract
  validations:
    required: true
- type: dropdown
  id: download2
  attributes:
    label: I want to
    options:
      - add
      - remove
      - change
  validations:
    required: true
- type: textarea
  id: iwantto
  attributes:
    label: ...
    description: 
    placeholder: 
    value: "Please say what you want"
  validations:
    required: true
- type: dropdown
  id: download3
  attributes:
    label: so that I can
    options:
      - view
      - analyse
      - score
      - select
      - report
  validations:
    required: true
- type: textarea
  id: achievegoal
  attributes:
    label: ...
    description: 
    placeholder: 
    value: "Please explain the end goal"
  validations:
    required: true
- type: textarea
  id: plainenglish
  attributes:
    label: In Plain English
    description: 
    placeholder: 
    value: "Add a simple description of the change, inclusing any key technical information such as CASE statements, logic, tables to reference "
  validations:
    required: true
- type: dropdown
  id: scope1
  attributes:
    label: Product
    options:
      - All Motor
      - Car
      - Bike
      - Van
      - Home
  validations:
    required: true
- type: dropdown
  id: scope2
  attributes:
    label: Quotes/Policies/Claims
    options:
      - Quotes
      - Policy
      - Claim
      - Market Data
      - Enrichment
  validations:
    required: false
- type: dropdown
  id: scope3
  attributes:
    label: Work Stream
    options:
      - Data Table (eg MPT/MQT)
      - Data String (eg QPDB/PropDB)
      - Pipeline/Automation Request
      - Analysis
  validations:
    required: false
- type: textarea
  id: acceptance
  attributes:
    label: Acceptance Criteria
    description: 
    placeholder: 
    value: "you need to explain here what success looks like. Anything NOT listed might not be caught in the test coverage, so make sure you list everything you can think of. "
  validations:
    required: true
